//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Serializable]
    public partial class Cart
    {
        public string UserName { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantities { get; set; }

        [NotMapped]
        public string ProductNameDisplay { get; set; }
        [NotMapped]
        public string ProductImagePathDisplay { get; set; }
        [NotMapped]
        public string ProductCategoryDisplay { get; set; }
        [NotMapped]
        public decimal ProductPriceDisplay { get; set; }
        [NotMapped]
        public decimal TotalPriceDisplay { get; set; }
    }
}
