//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DeliveryDetail
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Không được để trống tên người nhận")]
        [DisplayName("Tên người nhận")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Không được để trống địa chỉ")]
        [DisplayName("Địa chỉ giao hàng")]
        public string Adress { get; set; }
        public string UserName { get; set; }
        [Required(ErrorMessage = "Không được để trống số điện thoại")]
        [DisplayName("Số điện thoại người nhận")]
        public string PhoneNumber { get; set; }
    }
}
