//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Discount
    {   
        [Required]
        public int ID { get; set; }
        [Required]
        [DisplayName("Mã khuyến mãi")]
        public string Code { get; set; }
        [Required]
        [DisplayName("Tên khuyến mãi")]
        public string NameDisplay { get; set; }
        [Required]
        [DisplayName("Giá trị khuyến mãi")]
        public double Value { get; set; }
        [Required]
        [DisplayName("Thời gian bắt đầu")]
        public System.DateTime StartDate { get; set; }
        [Required]
        [DisplayName("Thời gian kết thúc")]
        public System.DateTime EndDate { get; set; }
    }
}
