//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        public int ID { get; set; }
        [DisplayName("Danh mục")]
        public int CategoryID { get; set; }
        [Required]
        [DisplayName("Tên sản phẩm")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Giá")]
        public decimal Price { get; set; }
        [DisplayName("Ảnh minh họa")]
        public string ImagePath { get; set; }

        [NotMapped]
        public string CategoryNameDisplay { get; set; }
        [NotMapped]
        public string AlterImage { get; set; }
    }
}
